version: "2"
services:
  app:
    container_name: "clients.api"
    restart: always
    build: .
    environment:
      - MONGO_URI=mongodb://mongo/clients
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    command: npm start

  mongo:
    container_name: "mongo"
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet